name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live (full)
      run: |
        sudo apt-get update
        # Install a full TeX Live to ensure all CTAN packages (e.g. physics.sty) are available.
        # This is larger and will increase CI runtime but avoids missing-package failures.
        sudo apt-get install -y latexmk texlive-full biber

    - name: Build PDF with latexmk
      working-directory: ${{ github.workspace }}
      run: |
        latexmk -pdf -interaction=nonstopmode -synctex=1 main.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: linear-algebra-book-pdf
        path: |
          main.pdf
